# Lynkby API Wrangler Configuration Template
# Copy this file to wrangler.toml and fill in your actual values
# NEVER commit actual secrets to version control!

name = "lynkby-api"
main = "src/workers/index.ts"
compatibility_date = "2025-08-01"
compatibility_flags = [ "nodejs_compat" ]

# KV Namespaces
[[kv_namespaces]]
binding = "KV_CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# R2 Buckets
[[r2_buckets]]
binding = "R2_ASSETS"
bucket_name = "lynkby-assets"

# Queues
[queues]
[[queues.consumers]]
queue = "tiktok-sync"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "tiktok-sync-dlq"

# Observsbility
[observability.logs]
enabled = true

# Development Environment
[env.development]
name = "lynkby-api-dev"

# Environment variables for development
[env.development.vars]
NODE_ENV = "development"
# APP_BASE=http://localhost:3001
# REVALIDATE_SECRET = "your-production-revalidate-secret-here"

# JWT_SECRET = "your-production-jwt-secret-must-be-at-least-32-chars-long"
# JWT_EXPIRES_IN = "7d"

# SENTRY_DSN = "https://your-production-sentry-dsn@sentry.io/project-id"

# DATABASE_URL = "https://your-production-database-url"
# DIRECT_URL = "https://your-production-direct-url"

# Stripe Configuration
# STRIPE_SECRET_KEY="sk_test_your_stripe_test_key_here"
# STRIPE_WEBHOOK_SECRET="whsec_your_webhook_secret_here"

# TikTok Configuration
# TIKTOK_CLIENT_KEY="your_tiktok_client_key_here"
# TIKTOK_CLIENT_SECRET="your_tiktok_client_secret_here"

# Production Environment
[env.production]
name = "lynkby-api"

# Environment variables for production
[env.production.vars]
NODE_ENV = "production"
# APP_BASE=http://localhost:3001
# REVALIDATE_SECRET = "your-production-revalidate-secret-here"

# JWT_SECRET = "your-production-jwt-secret-must-be-at-least-32-chars-long"
# JWT_EXPIRES_IN = "7d"

# SENTRY_DSN = "https://your-production-sentry-dsn@sentry.io/project-id"

# DATABASE_URL = "https://your-production-database-url"
# DIRECT_URL = "https://your-production-direct-url"

# Stripe Configuration
# STRIPE_SECRET_KEY="sk_test_your_stripe_test_key_here"
# STRIPE_WEBHOOK_SECRET="whsec_your_webhook_secret_here"

# TikTok Configuration
# TIKTOK_CLIENT_KEY="your_tiktok_client_key_here"
# TIKTOK_CLIENT_SECRET="your_tiktok_client_secret_here"

RESEND_API_KEY=123
SMTP_HOST=smtp.zoho.com
SMTP_PORT=465
SMTP_USER=exampl@zoho.com
SMTP_PASS=passowd
SMTP_FROM=exampl@zoho.com

# Cron triggers
[triggers]
crons = ["0 */6 * * *"] # Every 6 hours

 [[kv_namespaces]]
   binding = "KV_CACHE"
   id = "your-actual-kv-namespace-id"
   preview_id = "your-actual-preview-kv-namespace-id"
